import { chromium, devices } from "playwright";
const base = process.argv[2] ?? "http://localhost:3100";
const out = process.argv[3] ?? "/tmp";
const browser = await chromium.launch();
const ctx = await browser.newContext({ ...devices["iPhone 13"], deviceScaleFactor: 2 });
const page = await ctx.newPage();
const errors = [];
page.on("console", (m) => m.type() === "error" && errors.push(m.text()));
page.on("pageerror", (e) => errors.push(String(e)));
await page.goto(`${base}/order/table-07`, { waitUntil: "load" });
await page.getByText("Live", { exact: true }).first().waitFor({ timeout: 15000 });
await page.getByRole("button", { name: "Matcha", exact: true }).click();
await page.waitForTimeout(700);
await page.getByRole("button", { name: /^Iced Matcha, EGP 160/ }).click();
await page.waitForTimeout(500);
await page.getByRole("radio", { name: /Oat milk/ }).click();
await page.getByRole("radio", { name: /Less ice/ }).click();
await page.screenshot({ path: `${out}/flow-1-item.png` });
await page.getByRole("button", { name: /Add to order/ }).click();
await page.waitForTimeout(900);
await page.screenshot({ path: `${out}/flow-2-upsell.png` });
await page.getByRole("dialog").getByRole("button", { name: /^Add Maple Syrup/ }).click();
await page.waitForTimeout(500);
await page.getByRole("dialog").getByRole("button", { name: /View order/ }).click();
await page.waitForTimeout(700);
await page.screenshot({ path: `${out}/flow-3-cart.png` });
await page.getByRole("dialog").getByRole("button", { name: /^Checkout/ }).click();
await page.waitForTimeout(600);
await page.screenshot({ path: `${out}/flow-4-checkout.png` });
await page.getByRole("dialog").getByRole("button", { name: /^Pay EGP/ }).click();
await page.waitForSelector('[data-testid="order-stage"]', { timeout: 10000 });
await page.waitForTimeout(800);
await page.screenshot({ path: `${out}/flow-5-tracking.png` });
console.log("stage:", await page.textContent('[data-testid="order-stage"]'));
if (errors.length) console.log("ERRORS:\n" + errors.join("\n"));
await browser.close();
